#!/usr/bin/env bash
#
# Generate moved.tf for the count -> for_each migration of extra secrets in
# terraform-aws-hasura-cluster.
#
# Reads the current Terraform state for the two count-indexed resources:
#   <module>.aws_secretsmanager_secret.other_secrets[N]
#   <module>.aws_secretsmanager_secret.actions_endpoints_secrets[N]
# and emits `moved` blocks pointing each indexed instance (plus its
# corresponding _version instance) at the new name-keyed address.
#
# The user-supplied secret name is recovered from the AWS Secrets Manager
# `name` attribute by stripping the `<env_name>-<app_name>-` prefix the module
# adds. The prefix is derived automatically from the ECS cluster resource in
# state (always named `${env_name}-${app_name}-hasura-cluster`).
#
# Run from your root module (the directory containing the `module "..." { ... }`
# block that calls this module). The state for that root must be initialized
# already.
#
# Usage:
#   scripts/generate-secret-moves.sh <module-address> [out-file]
#
# Examples:
#   scripts/generate-secret-moves.sh module.hasura moved.tf
#   scripts/generate-secret-moves.sh module.hasura           # stdout
#
# After applying the resulting moved.tf, delete it (moved blocks are one-shot).

set -euo pipefail

usage() {
  sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
  exit "${1:-2}"
}

case "${1:-}" in
  -h|--help) usage 0 ;;
esac

MODULE_ADDR="${1:?missing module address (e.g. module.hasura). See --help.}"
OUT_FILE="${2:-}"

# Strip trailing dot if user passed "module.hasura."
MODULE_ADDR="${MODULE_ADDR%.}"

if ! command -v terraform >/dev/null 2>&1; then
  echo "error: terraform not found on PATH" >&2
  exit 1
fi

STATE_LIST="$(terraform state list)"

# Derive the prefix from the ECS cluster name, which this module always sets to
# "${env_name}-${app_name}-hasura-cluster".
CLUSTER_ADDR="${MODULE_ADDR}.aws_ecs_cluster.hasura"
CLUSTER_NAME="$(terraform state show -no-color "$CLUSTER_ADDR" \
  | awk -F'"' '/^[[:space:]]+name[[:space:]]*=/{print $2; exit}')"
if [[ -z "$CLUSTER_NAME" ]]; then
  echo "error: could not read name from $CLUSTER_ADDR" >&2
  echo "       ensure the module has been applied and the module address is correct" >&2
  exit 1
fi
PREFIX="${CLUSTER_NAME%-hasura-cluster}-"

# Print one paired moved block (secret + secret_version) for a given count
# resource. $1 = bare resource name e.g. "aws_secretsmanager_secret.other_secrets"
emit_pair_moves() {
  local secret_res="$1"
  local version_res="${secret_res/aws_secretsmanager_secret./aws_secretsmanager_secret_version.}"

  # Match only count-indexed addresses ([N]); skip anything already keyed.
  local addresses
  addresses="$(printf '%s\n' "$STATE_LIST" \
    | grep -E "^${MODULE_ADDR//./\\.}\.${secret_res//./\\.}\[[0-9]+\]$" || true)"

  if [[ -z "$addresses" ]]; then
    echo "# No count-indexed instances found for ${MODULE_ADDR}.${secret_res}" >&2
    return 0
  fi

  while IFS= read -r addr; do
    local idx aws_name key
    idx="${addr##*[}"; idx="${idx%]}"

    aws_name="$(terraform state show -no-color "$addr" \
      | awk -F'"' '/^[[:space:]]+name[[:space:]]*=/{print $2; exit}')"

    if [[ -z "$aws_name" ]]; then
      echo "error: could not read name from $addr" >&2
      exit 1
    fi
    if [[ "$aws_name" != "${PREFIX}"* ]]; then
      echo "error: secret name '$aws_name' does not start with prefix '$PREFIX'" >&2
      echo "       (check that env_name and app_name match this state)" >&2
      exit 1
    fi
    key="${aws_name#$PREFIX}"

    cat <<EOF
moved {
  from = ${MODULE_ADDR}.${secret_res}[${idx}]
  to   = ${MODULE_ADDR}.${secret_res}["${key}"]
}

moved {
  from = ${MODULE_ADDR}.${version_res}[${idx}]
  to   = ${MODULE_ADDR}.${version_res}["${key}"]
}

EOF
  done <<< "$addresses"
}

generate() {
  cat <<EOF
# Generated by scripts/generate-secret-moves.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Module:    ${MODULE_ADDR}
# Prefix:    ${PREFIX}
#
# Apply once, then delete this file.

EOF
  emit_pair_moves "aws_secretsmanager_secret.other_secrets"
  emit_pair_moves "aws_secretsmanager_secret.actions_endpoints_secrets"
}

if [[ -n "$OUT_FILE" ]]; then
  generate > "$OUT_FILE"
  echo "wrote $OUT_FILE" >&2
else
  generate
fi
